### ISSUE TITLE
在运行mobile 项目时发现一张表字段对不上，这张表在mysql中并不存在，请问这是在哪生成的表？感谢解答

### ISSUE THREAD

**Issue by techeaven** [zohar001/runscore#5]
![image](https://user-images.githubusercontent.com/44140173/67700222-81632c80-f9e8-11e9-94b6-9e98a5d613d5.png)

**Comment by techeaven** [comment]
我发现这是一个视图 视图缺少一个rebateAmount的字段，请问我需要怎么去修改它呢？

**Comment by zohar001** [comment]
把视图改下就行了

**Comment by techeaven** [comment]
好的 谢谢你

zohar001 <notifications@github.com> 于2019年10月29日周二 上午9:43写道：
